### ISSUE TITLE
Arrary contains NaN or infinity

### ISSUE THREAD

**Issue by Sharonno** [tmadl/linear-SVM-on-top-of-CNN-example#1]
thank you for the tutorial which I followed step by step.However something went wrong in the last few steps:
![screenshot from 2015-10-29 09 46 08](https://cloud.githubusercontent.com/assets/9607594/10809631/91dccee8-7e33-11e5-91d8-309a6281db87.png)
I tried to find the reason so I printed the probability using CNN to predict,but it seemed unnormal:
![screenshot from 2015-10-29 09 42 34](https://cloud.githubusercontent.com/assets/9607594/10809677/f583601a-7e33-11e5-93c0-4e0ea6c5baf0.png)
then I had a look at the feature obtained of the specified layer(pool5/7x7_s1) which was also unnormal:
![screenshot from 2015-10-29 09 43 42](https://cloud.githubusercontent.com/assets/9607594/10809749/8789a6d6-7e34-11e5-8486-9b5e042afaf4.png)
![screenshot from 2015-10-29 09 45 06](https://cloud.githubusercontent.com/assets/9607594/10809772/ad49c838-7e34-11e5-9505-19cfea2a7d6d.png)
I have no idea how to deal with the problem.Could you please help me ,ThX a lot !

**Comment by Sharonno** [comment]
I have gotten the anwser , i did not flatten the feature.thank you

**Comment by tmadl** [comment]
Thanks a lot for pointing this out! I've fixed the code (to call flatten() on the feature array before prediction)
